-- Prices for the Shop's new Weapons/Armor tabs (see ShopPanel.tsx) — a simple
-- placeholder formula (roughly 5x the item's main stat value), same "clearly
-- flagged, not tuned" status as every other economy number in this game
-- (arrow prices, monster gold rewards, Forge upgrade costs, etc.).

alter table public.item_templates add column if not exists price integer not null default 0;
alter table public.item_templates add constraint item_templates_price_check check (price >= 0);

update public.item_templates set price = 35 where name = 'Sapling Bow' and required_level = 8;
update public.item_templates set price = 50 where name = 'Ranger''s Bow' and required_level = 15;
update public.item_templates set price = 65 where name = 'Thornwood Bow' and required_level = 20;
update public.item_templates set price = 85 where name = 'Evergreen Bow' and required_level = 25;
update public.item_templates set price = 100 where name = 'Stonewood Bow' and required_level = 30;
update public.item_templates set price = 120 where name = 'Gale Bow' and required_level = 35;
update public.item_templates set price = 145 where name = 'Vermil Bow' and required_level = 40;
update public.item_templates set price = 165 where name = 'Ram''s Horn Bow' and required_level = 45;
update public.item_templates set price = 190 where name = 'Sovereign Bow' and required_level = 50;
update public.item_templates set price = 215 where name = 'Farreach Bow' and required_level = 55;
update public.item_templates set price = 245 where name = 'Drover''s Bow' and required_level = 60;
update public.item_templates set price = 270 where name = 'Forgesteel Bow' and required_level = 65;
update public.item_templates set price = 300 where name = 'Windwing Bow' and required_level = 70;
update public.item_templates set price = 335 where name = 'Stripeback Bow' and required_level = 75;
update public.item_templates set price = 365 where name = 'Heartwood Bow' and required_level = 80;
update public.item_templates set price = 400 where name = 'Runed Bow' and required_level = 85;
update public.item_templates set price = 440 where name = 'Starfall Bow' and required_level = 90;
update public.item_templates set price = 475 where name = 'Nightglow Bow' and required_level = 95;
update public.item_templates set price = 515 where name = 'Rosemark Bow' and required_level = 100;
update public.item_templates set price = 555 where name = 'Wyrmstring Bow' and required_level = 105;
update public.item_templates set price = 600 where name = 'Timeworn Bow' and required_level = 110;
update public.item_templates set price = 640 where name = 'Skyborne Bow' and required_level = 115;
update public.item_templates set price = 685 where name = 'Sorcerous Bow' and required_level = 120;
update public.item_templates set price = 695 where name = 'Sorcerous Bow' and required_level = 121;
update public.item_templates set price = 705 where name = 'Sorcerous Bow' and required_level = 122;
update public.item_templates set price = 715 where name = 'Sorcerous Bow' and required_level = 123;
update public.item_templates set price = 725 where name = 'Sorcerous Bow' and required_level = 124;
update public.item_templates set price = 735 where name = 'Emberwing Bow' and required_level = 125;
update public.item_templates set price = 745 where name = 'Emberwing Bow' and required_level = 126;
update public.item_templates set price = 755 where name = 'Emberwing Bow' and required_level = 127;
update public.item_templates set price = 765 where name = 'Emberwing Bow' and required_level = 128;
update public.item_templates set price = 770 where name = 'Emberwing Bow' and required_level = 129;
update public.item_templates set price = 780 where name = 'Voidcaller Bow' and required_level = 130;
update public.item_templates set price = 10 where name = 'Tin Ring' and required_level = 1;
update public.item_templates set price = 30 where name = 'Brass Ring' and required_level = 10;
update public.item_templates set price = 50 where name = 'Pewter Ring' and required_level = 20;
update public.item_templates set price = 75 where name = 'Gilded Ring' and required_level = 30;
update public.item_templates set price = 105 where name = 'Violet Ring' and required_level = 40;
update public.item_templates set price = 135 where name = 'Bonewhite Ring' and required_level = 50;
update public.item_templates set price = 170 where name = 'Verdant Ring' and required_level = 60;
update public.item_templates set price = 205 where name = 'Opal Ring' and required_level = 70;
update public.item_templates set price = 245 where name = 'Banded Ring' and required_level = 80;
update public.item_templates set price = 290 where name = 'Glass Ring' and required_level = 90;
update public.item_templates set price = 335 where name = 'Facet Ring' and required_level = 100;
update public.item_templates set price = 385 where name = 'Wyrmscale Ring' and required_level = 110;
update public.item_templates set price = 415 where name = 'Weeping Ring' and required_level = 116;
update public.item_templates set price = 440 where name = 'Oathbound Ring' and required_level = 121;
update public.item_templates set price = 470 where name = 'Stormcaller Ring' and required_level = 126;
update public.item_templates set price = 15 where name = 'Wisp Necklace' and required_level = 7;
update public.item_templates set price = 35 where name = 'Locket Necklace' and required_level = 17;
update public.item_templates set price = 55 where name = 'Twine Necklace' and required_level = 27;
update public.item_templates set price = 75 where name = 'Emerald Necklace' and required_level = 37;
update public.item_templates set price = 95 where name = 'Quartz Necklace' and required_level = 45;
update public.item_templates set price = 110 where name = 'Sunmetal Necklace' and required_level = 52;
update public.item_templates set price = 150 where name = 'Whitesteel Necklace' and required_level = 67;
update public.item_templates set price = 195 where name = 'Obsidian Necklace' and required_level = 82;
update public.item_templates set price = 245 where name = 'Serpent''s Necklace' and required_level = 97;
update public.item_templates set price = 300 where name = 'Reliquary Necklace' and required_level = 112;
update public.item_templates set price = 330 where name = 'Umbral Necklace' and required_level = 120;
update public.item_templates set price = 350 where name = 'Reverie Necklace' and required_level = 125;
update public.item_templates set price = 370 where name = 'Cyclone Necklace' and required_level = 130;
update public.item_templates set price = 20 where name = 'Rawhide Boots' and required_level = 10;
update public.item_templates set price = 30 where name = 'Fawnskin Boots' and required_level = 20;
update public.item_templates set price = 45 where name = 'Padded Boots' and required_level = 30;
update public.item_templates set price = 55 where name = 'Hawkstep Boots' and required_level = 40;
update public.item_templates set price = 70 where name = 'Featherstep Boots' and required_level = 50;
update public.item_templates set price = 80 where name = 'Scalehide Boots' and required_level = 60;
update public.item_templates set price = 95 where name = 'Viperskin Boots' and required_level = 70;
update public.item_templates set price = 105 where name = 'Prowler Boots' and required_level = 80;
update public.item_templates set price = 120 where name = 'Spotted Boots' and required_level = 90;
update public.item_templates set price = 130 where name = 'Direbeast Boots' and required_level = 100;
update public.item_templates set price = 145 where name = 'Nimble Boots' and required_level = 110;
update public.item_templates set price = 155 where name = 'Charmed Boots' and required_level = 120;
update public.item_templates set price = 160 where name = 'Liberty Boots' and required_level = 124;
update public.item_templates set price = 165 where name = 'Frostbite Boots' and required_level = 129;
update public.item_templates set price = 45 where name = 'Mole Hat' and required_level = 22;
update public.item_templates set price = 75 where name = 'Lynx Hat' and required_level = 37;
update public.item_templates set price = 110 where name = 'Coyote Hat' and required_level = 52;
update public.item_templates set price = 135 where name = 'Ocelot Hat' and required_level = 62;
update public.item_templates set price = 165 where name = 'Simian Hat' and required_level = 72;
update public.item_templates set price = 195 where name = 'Ferret Hat' and required_level = 82;
update public.item_templates set price = 230 where name = 'Stag Hat' and required_level = 92;
update public.item_templates set price = 260 where name = 'Bullhide Hat' and required_level = 102;
update public.item_templates set price = 290 where name = 'Talon Hat' and required_level = 110;
update public.item_templates set price = 315 where name = 'Finhead Hat' and required_level = 117;
update public.item_templates set price = 330 where name = 'Cinderplume Hat' and required_level = 120;
update public.item_templates set price = 335 where name = 'Wrenfeather Hat' and required_level = 121;
update public.item_templates set price = 335 where name = 'Wrenfeather Hat' and required_level = 122;
update public.item_templates set price = 340 where name = 'Wrenfeather Hat' and required_level = 123;
update public.item_templates set price = 345 where name = 'Wrenfeather Hat' and required_level = 124;
update public.item_templates set price = 350 where name = 'Wrenfeather Hat' and required_level = 125;
update public.item_templates set price = 355 where name = 'Vigor Hat' and required_level = 126;
update public.item_templates set price = 355 where name = 'Vigor Hat' and required_level = 127;
update public.item_templates set price = 360 where name = 'Vigor Hat' and required_level = 128;
update public.item_templates set price = 365 where name = 'Vigor Hat' and required_level = 129;
update public.item_templates set price = 370 where name = 'Vigor Hat' and required_level = 130;
update public.item_templates set price = 50 where name = 'Fawnhide Coat' and required_level = 15;
update public.item_templates set price = 90 where name = 'Vixen Coat' and required_level = 27;
update public.item_templates set price = 150 where name = 'Timberwolf Coat' and required_level = 42;
update public.item_templates set price = 215 where name = 'Dappled Coat' and required_level = 57;
update public.item_templates set price = 265 where name = 'Silverback Coat' and required_level = 67;
update public.item_templates set price = 320 where name = 'Quilted Coat' and required_level = 77;
update public.item_templates set price = 380 where name = 'Finscale Coat' and required_level = 87;
update public.item_templates set price = 440 where name = 'Hidebound Coat' and required_level = 97;
update public.item_templates set price = 505 where name = 'Skyfeather Coat' and required_level = 107;
update public.item_templates set price = 540 where name = 'Wyrmhide Coat' and required_level = 112;
update public.item_templates set price = 600 where name = 'Emberplate Coat' and required_level = 120;
update public.item_templates set price = 605 where name = 'Glacial Coat' and required_level = 121;
update public.item_templates set price = 615 where name = 'Glacial Coat' and required_level = 122;
update public.item_templates set price = 620 where name = 'Glacial Coat' and required_level = 123;
update public.item_templates set price = 630 where name = 'Glacial Coat' and required_level = 124;
update public.item_templates set price = 635 where name = 'Glacial Coat' and required_level = 125;
update public.item_templates set price = 645 where name = 'Sunforged Coat' and required_level = 126;
update public.item_templates set price = 650 where name = 'Sunforged Coat' and required_level = 127;
update public.item_templates set price = 660 where name = 'Sunforged Coat' and required_level = 128;
update public.item_templates set price = 665 where name = 'Sunforged Coat' and required_level = 129;
update public.item_templates set price = 675 where name = 'Sunforged Coat' and required_level = 130;

-- The original placeholder weapon, seeded before this column existed.
update public.item_templates set price = 25 where name = 'Wooden Sword';
