-- First real gear catalog (see CLAUDE.md's Gear system section) — replaces the
-- single placeholder "Wooden Sword" era with 117 original items across 6 slot
-- types (weapon/bow, ring, necklace, boots, hat, coat). Names and stat numbers
-- are original — not the Conquer Online reference data the user pulled earlier
-- (see reference/conquer-items/), which was used only as a rough pattern for
-- pacing (how many items per level bracket, how steeply stats should climb),
-- not copied directly. Level 130 is the current cap; nothing above it exists.
--
-- required_level/required_class are display/flavor only for now — nothing
-- currently gates equipping on either (no equip-requirement check exists, and
-- only Main Hand is a functional equip slot at all — see EquipmentPanel.tsx).
-- required_class 'hunter' marks the Archer-only hat/coat slots; null means any
-- class. base_stats holds each item's Normal-tier baseline only — quality tier
-- scaling is applied dynamically via QUALITY_STAT_MULTIPLIERS in
-- equipmentBonus.ts, not baked into a separate row per tier.

alter table public.item_templates
  add column if not exists required_level integer not null default 1,
  add column if not exists required_class text;

insert into public.item_templates (name, slot_type, base_stats, required_level, required_class) values
  ('Sapling Bow', 'weapon', '{"physical_attack":7}'::jsonb, 8, null),
  ('Ranger''s Bow', 'weapon', '{"physical_attack":10}'::jsonb, 15, null),
  ('Thornwood Bow', 'weapon', '{"physical_attack":13}'::jsonb, 20, null),
  ('Evergreen Bow', 'weapon', '{"physical_attack":17}'::jsonb, 25, null),
  ('Stonewood Bow', 'weapon', '{"physical_attack":20}'::jsonb, 30, null),
  ('Gale Bow', 'weapon', '{"physical_attack":24}'::jsonb, 35, null),
  ('Vermil Bow', 'weapon', '{"physical_attack":29}'::jsonb, 40, null),
  ('Ram''s Horn Bow', 'weapon', '{"physical_attack":33}'::jsonb, 45, null),
  ('Sovereign Bow', 'weapon', '{"physical_attack":38}'::jsonb, 50, null),
  ('Farreach Bow', 'weapon', '{"physical_attack":43}'::jsonb, 55, null),
  ('Drover''s Bow', 'weapon', '{"physical_attack":49}'::jsonb, 60, null),
  ('Forgesteel Bow', 'weapon', '{"physical_attack":54}'::jsonb, 65, null),
  ('Windwing Bow', 'weapon', '{"physical_attack":60}'::jsonb, 70, null),
  ('Stripeback Bow', 'weapon', '{"physical_attack":67}'::jsonb, 75, null),
  ('Heartwood Bow', 'weapon', '{"physical_attack":73}'::jsonb, 80, null),
  ('Runed Bow', 'weapon', '{"physical_attack":80}'::jsonb, 85, null),
  ('Starfall Bow', 'weapon', '{"physical_attack":88}'::jsonb, 90, null),
  ('Nightglow Bow', 'weapon', '{"physical_attack":95}'::jsonb, 95, null),
  ('Rosemark Bow', 'weapon', '{"physical_attack":103}'::jsonb, 100, null),
  ('Wyrmstring Bow', 'weapon', '{"physical_attack":111}'::jsonb, 105, null),
  ('Timeworn Bow', 'weapon', '{"physical_attack":120}'::jsonb, 110, null),
  ('Skyborne Bow', 'weapon', '{"physical_attack":128}'::jsonb, 115, null),
  ('Sorcerous Bow', 'weapon', '{"physical_attack":137}'::jsonb, 120, null),
  ('Sorcerous Bow', 'weapon', '{"physical_attack":139}'::jsonb, 121, null),
  ('Sorcerous Bow', 'weapon', '{"physical_attack":141}'::jsonb, 122, null),
  ('Sorcerous Bow', 'weapon', '{"physical_attack":143}'::jsonb, 123, null),
  ('Sorcerous Bow', 'weapon', '{"physical_attack":145}'::jsonb, 124, null),
  ('Emberwing Bow', 'weapon', '{"physical_attack":147}'::jsonb, 125, null),
  ('Emberwing Bow', 'weapon', '{"physical_attack":149}'::jsonb, 126, null),
  ('Emberwing Bow', 'weapon', '{"physical_attack":151}'::jsonb, 127, null),
  ('Emberwing Bow', 'weapon', '{"physical_attack":153}'::jsonb, 128, null),
  ('Emberwing Bow', 'weapon', '{"physical_attack":154}'::jsonb, 129, null),
  ('Voidcaller Bow', 'weapon', '{"physical_attack":156}'::jsonb, 130, null),
  ('Tin Ring', 'ring', '{"physical_attack":2}'::jsonb, 1, null),
  ('Brass Ring', 'ring', '{"physical_attack":6}'::jsonb, 10, null),
  ('Pewter Ring', 'ring', '{"physical_attack":10}'::jsonb, 20, null),
  ('Gilded Ring', 'ring', '{"physical_attack":15}'::jsonb, 30, null),
  ('Violet Ring', 'ring', '{"physical_attack":21}'::jsonb, 40, null),
  ('Bonewhite Ring', 'ring', '{"physical_attack":27}'::jsonb, 50, null),
  ('Verdant Ring', 'ring', '{"physical_attack":34}'::jsonb, 60, null),
  ('Opal Ring', 'ring', '{"physical_attack":41}'::jsonb, 70, null),
  ('Banded Ring', 'ring', '{"physical_attack":49}'::jsonb, 80, null),
  ('Glass Ring', 'ring', '{"physical_attack":58}'::jsonb, 90, null),
  ('Facet Ring', 'ring', '{"physical_attack":67}'::jsonb, 100, null),
  ('Wyrmscale Ring', 'ring', '{"physical_attack":77}'::jsonb, 110, null),
  ('Weeping Ring', 'ring', '{"physical_attack":83}'::jsonb, 116, null),
  ('Oathbound Ring', 'ring', '{"physical_attack":88}'::jsonb, 121, null),
  ('Stormcaller Ring', 'ring', '{"physical_attack":94}'::jsonb, 126, null),
  ('Wisp Necklace', 'necklace', '{"physical_defense":3}'::jsonb, 7, null),
  ('Locket Necklace', 'necklace', '{"physical_defense":7}'::jsonb, 17, null),
  ('Twine Necklace', 'necklace', '{"physical_defense":11}'::jsonb, 27, null),
  ('Emerald Necklace', 'necklace', '{"physical_defense":15}'::jsonb, 37, null),
  ('Quartz Necklace', 'necklace', '{"physical_defense":19}'::jsonb, 45, null),
  ('Sunmetal Necklace', 'necklace', '{"physical_defense":22}'::jsonb, 52, null),
  ('Whitesteel Necklace', 'necklace', '{"physical_defense":30}'::jsonb, 67, null),
  ('Obsidian Necklace', 'necklace', '{"physical_defense":39}'::jsonb, 82, null),
  ('Serpent''s Necklace', 'necklace', '{"physical_defense":49}'::jsonb, 97, null),
  ('Reliquary Necklace', 'necklace', '{"physical_defense":60}'::jsonb, 112, null),
  ('Umbral Necklace', 'necklace', '{"physical_defense":66}'::jsonb, 120, null),
  ('Reverie Necklace', 'necklace', '{"physical_defense":70}'::jsonb, 125, null),
  ('Cyclone Necklace', 'necklace', '{"physical_defense":74}'::jsonb, 130, null),
  ('Rawhide Boots', 'boots', '{"dodge":4}'::jsonb, 10, null),
  ('Fawnskin Boots', 'boots', '{"dodge":6}'::jsonb, 20, null),
  ('Padded Boots', 'boots', '{"dodge":9}'::jsonb, 30, null),
  ('Hawkstep Boots', 'boots', '{"dodge":11}'::jsonb, 40, null),
  ('Featherstep Boots', 'boots', '{"dodge":14}'::jsonb, 50, null),
  ('Scalehide Boots', 'boots', '{"dodge":16}'::jsonb, 60, null),
  ('Viperskin Boots', 'boots', '{"dodge":19}'::jsonb, 70, null),
  ('Prowler Boots', 'boots', '{"dodge":21}'::jsonb, 80, null),
  ('Spotted Boots', 'boots', '{"dodge":24}'::jsonb, 90, null),
  ('Direbeast Boots', 'boots', '{"dodge":26}'::jsonb, 100, null),
  ('Nimble Boots', 'boots', '{"dodge":29}'::jsonb, 110, null),
  ('Charmed Boots', 'boots', '{"dodge":31}'::jsonb, 120, null),
  ('Liberty Boots', 'boots', '{"dodge":32}'::jsonb, 124, null),
  ('Frostbite Boots', 'boots', '{"dodge":33}'::jsonb, 129, null),
  ('Mole Hat', 'hat', '{"physical_defense":9}'::jsonb, 22, 'hunter'),
  ('Lynx Hat', 'hat', '{"physical_defense":15}'::jsonb, 37, 'hunter'),
  ('Coyote Hat', 'hat', '{"physical_defense":22}'::jsonb, 52, 'hunter'),
  ('Ocelot Hat', 'hat', '{"physical_defense":27}'::jsonb, 62, 'hunter'),
  ('Simian Hat', 'hat', '{"physical_defense":33}'::jsonb, 72, 'hunter'),
  ('Ferret Hat', 'hat', '{"physical_defense":39}'::jsonb, 82, 'hunter'),
  ('Stag Hat', 'hat', '{"physical_defense":46}'::jsonb, 92, 'hunter'),
  ('Bullhide Hat', 'hat', '{"physical_defense":52}'::jsonb, 102, 'hunter'),
  ('Talon Hat', 'hat', '{"physical_defense":58}'::jsonb, 110, 'hunter'),
  ('Finhead Hat', 'hat', '{"physical_defense":63}'::jsonb, 117, 'hunter'),
  ('Cinderplume Hat', 'hat', '{"physical_defense":66}'::jsonb, 120, 'hunter'),
  ('Wrenfeather Hat', 'hat', '{"physical_defense":67}'::jsonb, 121, 'hunter'),
  ('Wrenfeather Hat', 'hat', '{"physical_defense":67}'::jsonb, 122, 'hunter'),
  ('Wrenfeather Hat', 'hat', '{"physical_defense":68}'::jsonb, 123, 'hunter'),
  ('Wrenfeather Hat', 'hat', '{"physical_defense":69}'::jsonb, 124, 'hunter'),
  ('Wrenfeather Hat', 'hat', '{"physical_defense":70}'::jsonb, 125, 'hunter'),
  ('Vigor Hat', 'hat', '{"physical_defense":71}'::jsonb, 126, 'hunter'),
  ('Vigor Hat', 'hat', '{"physical_defense":71}'::jsonb, 127, 'hunter'),
  ('Vigor Hat', 'hat', '{"physical_defense":72}'::jsonb, 128, 'hunter'),
  ('Vigor Hat', 'hat', '{"physical_defense":73}'::jsonb, 129, 'hunter'),
  ('Vigor Hat', 'hat', '{"physical_defense":74}'::jsonb, 130, 'hunter'),
  ('Fawnhide Coat', 'coat', '{"physical_defense":10}'::jsonb, 15, 'hunter'),
  ('Vixen Coat', 'coat', '{"physical_defense":18}'::jsonb, 27, 'hunter'),
  ('Timberwolf Coat', 'coat', '{"physical_defense":30}'::jsonb, 42, 'hunter'),
  ('Dappled Coat', 'coat', '{"physical_defense":43}'::jsonb, 57, 'hunter'),
  ('Silverback Coat', 'coat', '{"physical_defense":53}'::jsonb, 67, 'hunter'),
  ('Quilted Coat', 'coat', '{"physical_defense":64}'::jsonb, 77, 'hunter'),
  ('Finscale Coat', 'coat', '{"physical_defense":76}'::jsonb, 87, 'hunter'),
  ('Hidebound Coat', 'coat', '{"physical_defense":88}'::jsonb, 97, 'hunter'),
  ('Skyfeather Coat', 'coat', '{"physical_defense":101}'::jsonb, 107, 'hunter'),
  ('Wyrmhide Coat', 'coat', '{"physical_defense":108}'::jsonb, 112, 'hunter'),
  ('Emberplate Coat', 'coat', '{"physical_defense":120}'::jsonb, 120, 'hunter'),
  ('Glacial Coat', 'coat', '{"physical_defense":121}'::jsonb, 121, 'hunter'),
  ('Glacial Coat', 'coat', '{"physical_defense":123}'::jsonb, 122, 'hunter'),
  ('Glacial Coat', 'coat', '{"physical_defense":124}'::jsonb, 123, 'hunter'),
  ('Glacial Coat', 'coat', '{"physical_defense":126}'::jsonb, 124, 'hunter'),
  ('Glacial Coat', 'coat', '{"physical_defense":127}'::jsonb, 125, 'hunter'),
  ('Sunforged Coat', 'coat', '{"physical_defense":129}'::jsonb, 126, 'hunter'),
  ('Sunforged Coat', 'coat', '{"physical_defense":130}'::jsonb, 127, 'hunter'),
  ('Sunforged Coat', 'coat', '{"physical_defense":132}'::jsonb, 128, 'hunter'),
  ('Sunforged Coat', 'coat', '{"physical_defense":133}'::jsonb, 129, 'hunter'),
  ('Sunforged Coat', 'coat', '{"physical_defense":135}'::jsonb, 130, 'hunter');
