-- First real gear catalog entry for Twin-soul (Trojan), mirroring how
-- Hunter's and Wuxia's own catalogs were built. Original names, stat numbers
-- paced loosely off Conquer Online reference data in reference/conquer-
-- items/{clubs,swords,blades,coronets,mails}.md, not copied directly. All
-- required_class = 'twin-soul' (never null — Hunter must never see these).
--
-- Per the confirmed class mapping, Twin-soul (dual-wield melee) draws from
-- all three one-handed weapon families (Club/Sword/Blade) rather than one
-- exclusive family the way Hunter/Wuxia do — Juggernaut shares this same
-- pool in a later migration, under its own separate item_family keys per
-- family (club-twinsoul vs club-juggernaut, etc.) so the two classes' chain
-- advancement (level_upgrade) never crosses between them, even though the
-- name/stats are identical. The bare `sword` item_family is intentionally
-- avoided (already used by the legacy singleton Wooden Sword) — this real
-- chain uses `longsword-twinsoul` instead.
--
-- Off-hand weapon ("Twinblade") repurposes the second-hand slot
-- (slot_type='quiver', see 20260910000000_second_hand_slot_stats_in_combat.sql)
-- as Twin-soul's second dual-wielded item — its own distinct chain, not a
-- second copy of Club/Sword/Blade, since a template's slot_type fixes which
-- equip column it can go into.
--
-- All 4 weapon chains reuse Bow's exact physical_attack/dexterity curve
-- (see 20260730000000_add_gear_catalog.sql + 20260802020000_add_bow_ring_
-- dexterity.sql) for cross-class balance parity, same reasoning as Wuxia's
-- Backsword. Coronet/Mail reuse Hunter's Necklace/Coat defense curves,
-- same reasoning as Wuxia's Cap/Robe. Per the user: only the weapon chains
-- get the fine per-level 120-130 breakdown; Coronet/Mail use coarser
-- breakpoints instead.

insert into public.item_templates (name, slot_type, item_family, base_stats, required_level, required_class) values
  ('Rustcut Club', 'weapon', 'club-twinsoul', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'twin-soul'),
  ('Ironbound Club', 'weapon', 'club-twinsoul', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'twin-soul'),
  ('Steelfang Club', 'weapon', 'club-twinsoul', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'twin-soul'),
  ('Bloodedge Club', 'weapon', 'club-twinsoul', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'twin-soul'),
  ('Battleworn Club', 'weapon', 'club-twinsoul', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'twin-soul'),
  ('Warforged Club', 'weapon', 'club-twinsoul', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'twin-soul'),
  ('Grimsteel Club', 'weapon', 'club-twinsoul', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'twin-soul'),
  ('Ashfallen Club', 'weapon', 'club-twinsoul', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'twin-soul'),
  ('Direheart Club', 'weapon', 'club-twinsoul', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'twin-soul'),
  ('Bramblefang Club', 'weapon', 'club-twinsoul', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'twin-soul'),
  ('Nightstrike Club', 'weapon', 'club-twinsoul', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'twin-soul'),
  ('Frostbrand Club', 'weapon', 'club-twinsoul', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'twin-soul'),
  ('Stormedge Club', 'weapon', 'club-twinsoul', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'twin-soul'),
  ('Ironclad Club', 'weapon', 'club-twinsoul', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'twin-soul'),
  ('Bloodoath Club', 'weapon', 'club-twinsoul', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'twin-soul'),
  ('Grimward Club', 'weapon', 'club-twinsoul', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'twin-soul'),
  ('Skullrend Club', 'weapon', 'club-twinsoul', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'twin-soul'),
  ('Doomforge Club', 'weapon', 'club-twinsoul', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'twin-soul'),
  ('Wrathbound Club', 'weapon', 'club-twinsoul', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'twin-soul'),
  ('Shadowstrike Club', 'weapon', 'club-twinsoul', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'twin-soul'),
  ('Vengeance Club', 'weapon', 'club-twinsoul', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'twin-soul'),
  ('Warbringer Club', 'weapon', 'club-twinsoul', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'twin-soul'),
  ('Astral Club', 'weapon', 'club-twinsoul', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'twin-soul'),
  ('Astral Club', 'weapon', 'club-twinsoul', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'twin-soul'),
  ('Astral Club', 'weapon', 'club-twinsoul', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'twin-soul'),
  ('Astral Club', 'weapon', 'club-twinsoul', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'twin-soul'),
  ('Astral Club', 'weapon', 'club-twinsoul', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'twin-soul'),
  ('Celestial Club', 'weapon', 'club-twinsoul', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'twin-soul'),
  ('Celestial Club', 'weapon', 'club-twinsoul', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'twin-soul'),
  ('Celestial Club', 'weapon', 'club-twinsoul', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'twin-soul'),
  ('Celestial Club', 'weapon', 'club-twinsoul', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'twin-soul'),
  ('Celestial Club', 'weapon', 'club-twinsoul', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'twin-soul'),
  ('Eternity Club', 'weapon', 'club-twinsoul', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'twin-soul'),

  ('Rustcut Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'twin-soul'),
  ('Ironbound Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'twin-soul'),
  ('Steelfang Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'twin-soul'),
  ('Bloodedge Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'twin-soul'),
  ('Battleworn Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'twin-soul'),
  ('Warforged Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'twin-soul'),
  ('Grimsteel Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'twin-soul'),
  ('Ashfallen Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'twin-soul'),
  ('Direheart Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'twin-soul'),
  ('Bramblefang Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'twin-soul'),
  ('Nightstrike Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'twin-soul'),
  ('Frostbrand Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'twin-soul'),
  ('Stormedge Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'twin-soul'),
  ('Ironclad Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'twin-soul'),
  ('Bloodoath Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'twin-soul'),
  ('Grimward Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'twin-soul'),
  ('Skullrend Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'twin-soul'),
  ('Doomforge Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'twin-soul'),
  ('Wrathbound Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'twin-soul'),
  ('Shadowstrike Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'twin-soul'),
  ('Vengeance Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'twin-soul'),
  ('Warbringer Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'twin-soul'),
  ('Astral Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'twin-soul'),
  ('Astral Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'twin-soul'),
  ('Astral Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'twin-soul'),
  ('Astral Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'twin-soul'),
  ('Astral Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'twin-soul'),
  ('Celestial Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'twin-soul'),
  ('Celestial Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'twin-soul'),
  ('Celestial Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'twin-soul'),
  ('Celestial Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'twin-soul'),
  ('Celestial Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'twin-soul'),
  ('Eternity Sword', 'weapon', 'longsword-twinsoul', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'twin-soul'),

  ('Rustcut Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'twin-soul'),
  ('Ironbound Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'twin-soul'),
  ('Steelfang Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'twin-soul'),
  ('Bloodedge Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'twin-soul'),
  ('Battleworn Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'twin-soul'),
  ('Warforged Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'twin-soul'),
  ('Grimsteel Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'twin-soul'),
  ('Ashfallen Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'twin-soul'),
  ('Direheart Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'twin-soul'),
  ('Bramblefang Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'twin-soul'),
  ('Nightstrike Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'twin-soul'),
  ('Frostbrand Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'twin-soul'),
  ('Stormedge Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'twin-soul'),
  ('Ironclad Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'twin-soul'),
  ('Bloodoath Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'twin-soul'),
  ('Grimward Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'twin-soul'),
  ('Skullrend Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'twin-soul'),
  ('Doomforge Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'twin-soul'),
  ('Wrathbound Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'twin-soul'),
  ('Shadowstrike Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'twin-soul'),
  ('Vengeance Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'twin-soul'),
  ('Warbringer Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'twin-soul'),
  ('Astral Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'twin-soul'),
  ('Astral Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'twin-soul'),
  ('Astral Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'twin-soul'),
  ('Astral Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'twin-soul'),
  ('Astral Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'twin-soul'),
  ('Celestial Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'twin-soul'),
  ('Celestial Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'twin-soul'),
  ('Celestial Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'twin-soul'),
  ('Celestial Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'twin-soul'),
  ('Celestial Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'twin-soul'),
  ('Eternity Blade', 'weapon', 'blade-twinsoul', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'twin-soul'),

  ('Rustcut Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'twin-soul'),
  ('Ironbound Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'twin-soul'),
  ('Steelfang Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'twin-soul'),
  ('Bloodedge Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'twin-soul'),
  ('Battleworn Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'twin-soul'),
  ('Warforged Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'twin-soul'),
  ('Grimsteel Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'twin-soul'),
  ('Ashfallen Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'twin-soul'),
  ('Direheart Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'twin-soul'),
  ('Bramblefang Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'twin-soul'),
  ('Nightstrike Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'twin-soul'),
  ('Frostbrand Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'twin-soul'),
  ('Stormedge Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'twin-soul'),
  ('Ironclad Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'twin-soul'),
  ('Bloodoath Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'twin-soul'),
  ('Grimward Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'twin-soul'),
  ('Skullrend Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'twin-soul'),
  ('Doomforge Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'twin-soul'),
  ('Wrathbound Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'twin-soul'),
  ('Shadowstrike Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'twin-soul'),
  ('Vengeance Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'twin-soul'),
  ('Warbringer Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'twin-soul'),
  ('Astral Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'twin-soul'),
  ('Astral Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'twin-soul'),
  ('Astral Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'twin-soul'),
  ('Astral Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'twin-soul'),
  ('Astral Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'twin-soul'),
  ('Celestial Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'twin-soul'),
  ('Celestial Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'twin-soul'),
  ('Celestial Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'twin-soul'),
  ('Celestial Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'twin-soul'),
  ('Celestial Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'twin-soul'),
  ('Eternity Twinblade', 'quiver', 'offhand-twinsoul', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'twin-soul'),

  ('Rawhide Coronet', 'hat', 'coronet', '{"physical_defense":3}'::jsonb, 7, 'twin-soul'),
  ('Banded Coronet', 'hat', 'coronet', '{"physical_defense":7}'::jsonb, 17, 'twin-soul'),
  ('Ridged Coronet', 'hat', 'coronet', '{"physical_defense":11}'::jsonb, 27, 'twin-soul'),
  ('Ironbrow Coronet', 'hat', 'coronet', '{"physical_defense":15}'::jsonb, 37, 'twin-soul'),
  ('Warcrest Coronet', 'hat', 'coronet', '{"physical_defense":19}'::jsonb, 45, 'twin-soul'),
  ('Bloodguard Coronet', 'hat', 'coronet', '{"physical_defense":22}'::jsonb, 52, 'twin-soul'),
  ('Stormhelm Coronet', 'hat', 'coronet', '{"physical_defense":30}'::jsonb, 67, 'twin-soul'),
  ('Direplate Coronet', 'hat', 'coronet', '{"physical_defense":39}'::jsonb, 82, 'twin-soul'),
  ('Grimvisage Coronet', 'hat', 'coronet', '{"physical_defense":49}'::jsonb, 97, 'twin-soul'),
  ('Warlord Coronet', 'hat', 'coronet', '{"physical_defense":60}'::jsonb, 112, 'twin-soul'),
  ('Astral Coronet', 'hat', 'coronet', '{"physical_defense":66}'::jsonb, 120, 'twin-soul'),
  ('Celestial Coronet', 'hat', 'coronet', '{"physical_defense":70}'::jsonb, 125, 'twin-soul'),
  ('Eternity Coronet', 'hat', 'coronet', '{"physical_defense":74}'::jsonb, 130, 'twin-soul'),

  ('Rawhide Mail', 'coat', 'mail', '{"physical_defense":3,"magic_defense":2}'::jsonb, 7, 'twin-soul'),
  ('Banded Mail', 'coat', 'mail', '{"physical_defense":7,"magic_defense":4}'::jsonb, 17, 'twin-soul'),
  ('Ridged Mail', 'coat', 'mail', '{"physical_defense":11,"magic_defense":6}'::jsonb, 27, 'twin-soul'),
  ('Ironweave Mail', 'coat', 'mail', '{"physical_defense":15,"magic_defense":8}'::jsonb, 37, 'twin-soul'),
  ('Warplate Mail', 'coat', 'mail', '{"physical_defense":19,"magic_defense":10}'::jsonb, 45, 'twin-soul'),
  ('Bloodforged Mail', 'coat', 'mail', '{"physical_defense":22,"magic_defense":11}'::jsonb, 52, 'twin-soul'),
  ('Stormguard Mail', 'coat', 'mail', '{"physical_defense":30,"magic_defense":15}'::jsonb, 67, 'twin-soul'),
  ('Ashenplate Mail', 'coat', 'mail', '{"physical_defense":39,"magic_defense":20}'::jsonb, 82, 'twin-soul'),
  ('Grimhide Mail', 'coat', 'mail', '{"physical_defense":49,"magic_defense":25}'::jsonb, 97, 'twin-soul'),
  ('Warlord Mail', 'coat', 'mail', '{"physical_defense":60,"magic_defense":30}'::jsonb, 112, 'twin-soul'),
  ('Astral Mail', 'coat', 'mail', '{"physical_defense":66,"magic_defense":33}'::jsonb, 120, 'twin-soul'),
  ('Celestial Mail', 'coat', 'mail', '{"physical_defense":70,"magic_defense":35}'::jsonb, 125, 'twin-soul'),
  ('Eternity Mail', 'coat', 'mail', '{"physical_defense":74,"magic_defense":37}'::jsonb, 130, 'twin-soul');
