-- Final gear catalog entry of this pass, for Juggernaut (Warrior), mirroring
-- how Hunter's/Wuxia's/Twin-soul's own catalogs were built. Original names,
-- stat numbers paced loosely off Conquer Online reference data in
-- reference/conquer-items/{clubs,swords,blades,wands,helmets,armors,
-- shields}.md, not copied directly. All required_class = 'juggernaut' (never
-- null — Hunter must never see these).
--
-- Club/Sword/Blade repeat Twin-soul's exact same names/stats (they share one
-- conceptual weapon pool per the confirmed mapping) but under their own
-- item_family keys (-juggernaut suffix instead of -twinsoul) so chain
-- advancement never crosses between the two classes' otherwise-identical
-- items — see 20260911000000_twin_soul_gear_catalog.sql's own note on why.
--
-- Wand is Juggernaut's exclusive two-hander — reflavored from the source
-- reference data's caster "Wand" into a heavy two-handed maul (physical_
-- attack, not magic_attack) to fit Juggernaut's Strength-based "heavy tank"
-- design (Warrior starts with 0 Spirit, per classes.ts's attribute anchors,
-- so a magic-scaling weapon would fit poorly).
--
-- Shield uses the repurposed second-hand slot (slot_type='quiver', see
-- 20260910000000_second_hand_slot_stats_in_combat.sql) and is the one new
-- family this pass with a `max_hp` base_stats key (Shield's flat "Life"
-- stat, folded into max HP via EquipmentBonus.gearHpBonus). Modest values
-- relative to the attribute-derived HP curve — a placeholder like every
-- other stat number in this catalog, not balance-tested.
--
-- All 4 weapon chains (Club/Sword/Blade/Wand) reuse Bow's exact physical_
-- attack/dexterity curve, same cross-class-parity reasoning as every other
-- class's weapons this pass. Helmet/Armor reuse Hunter's Necklace/Coat
-- defense curves, same as Coronet/Mail did for Twin-soul. Shield uses its
-- own modest defense+HP curve. Per the user: only the weapon chains get the
-- fine per-level 120-130 breakdown — Shield/Helmet/Armor use the coarser
-- breakpoints instead.

insert into public.item_templates (name, slot_type, item_family, base_stats, required_level, required_class) values
  ('Rustcut Club', 'weapon', 'club-juggernaut', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'juggernaut'),
  ('Ironbound Club', 'weapon', 'club-juggernaut', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'juggernaut'),
  ('Steelfang Club', 'weapon', 'club-juggernaut', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'juggernaut'),
  ('Bloodedge Club', 'weapon', 'club-juggernaut', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'juggernaut'),
  ('Battleworn Club', 'weapon', 'club-juggernaut', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'juggernaut'),
  ('Warforged Club', 'weapon', 'club-juggernaut', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'juggernaut'),
  ('Grimsteel Club', 'weapon', 'club-juggernaut', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'juggernaut'),
  ('Ashfallen Club', 'weapon', 'club-juggernaut', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'juggernaut'),
  ('Direheart Club', 'weapon', 'club-juggernaut', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'juggernaut'),
  ('Bramblefang Club', 'weapon', 'club-juggernaut', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'juggernaut'),
  ('Nightstrike Club', 'weapon', 'club-juggernaut', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'juggernaut'),
  ('Frostbrand Club', 'weapon', 'club-juggernaut', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'juggernaut'),
  ('Stormedge Club', 'weapon', 'club-juggernaut', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'juggernaut'),
  ('Ironclad Club', 'weapon', 'club-juggernaut', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'juggernaut'),
  ('Bloodoath Club', 'weapon', 'club-juggernaut', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'juggernaut'),
  ('Grimward Club', 'weapon', 'club-juggernaut', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'juggernaut'),
  ('Skullrend Club', 'weapon', 'club-juggernaut', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'juggernaut'),
  ('Doomforge Club', 'weapon', 'club-juggernaut', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'juggernaut'),
  ('Wrathbound Club', 'weapon', 'club-juggernaut', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'juggernaut'),
  ('Shadowstrike Club', 'weapon', 'club-juggernaut', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'juggernaut'),
  ('Vengeance Club', 'weapon', 'club-juggernaut', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'juggernaut'),
  ('Warbringer Club', 'weapon', 'club-juggernaut', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'juggernaut'),
  ('Astral Club', 'weapon', 'club-juggernaut', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'juggernaut'),
  ('Astral Club', 'weapon', 'club-juggernaut', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'juggernaut'),
  ('Astral Club', 'weapon', 'club-juggernaut', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'juggernaut'),
  ('Astral Club', 'weapon', 'club-juggernaut', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'juggernaut'),
  ('Astral Club', 'weapon', 'club-juggernaut', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'juggernaut'),
  ('Celestial Club', 'weapon', 'club-juggernaut', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'juggernaut'),
  ('Celestial Club', 'weapon', 'club-juggernaut', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'juggernaut'),
  ('Celestial Club', 'weapon', 'club-juggernaut', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'juggernaut'),
  ('Celestial Club', 'weapon', 'club-juggernaut', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'juggernaut'),
  ('Celestial Club', 'weapon', 'club-juggernaut', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'juggernaut'),
  ('Eternity Club', 'weapon', 'club-juggernaut', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'juggernaut'),

  ('Rustcut Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'juggernaut'),
  ('Ironbound Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'juggernaut'),
  ('Steelfang Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'juggernaut'),
  ('Bloodedge Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'juggernaut'),
  ('Battleworn Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'juggernaut'),
  ('Warforged Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'juggernaut'),
  ('Grimsteel Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'juggernaut'),
  ('Ashfallen Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'juggernaut'),
  ('Direheart Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'juggernaut'),
  ('Bramblefang Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'juggernaut'),
  ('Nightstrike Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'juggernaut'),
  ('Frostbrand Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'juggernaut'),
  ('Stormedge Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'juggernaut'),
  ('Ironclad Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'juggernaut'),
  ('Bloodoath Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'juggernaut'),
  ('Grimward Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'juggernaut'),
  ('Skullrend Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'juggernaut'),
  ('Doomforge Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'juggernaut'),
  ('Wrathbound Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'juggernaut'),
  ('Shadowstrike Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'juggernaut'),
  ('Vengeance Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'juggernaut'),
  ('Warbringer Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'juggernaut'),
  ('Astral Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'juggernaut'),
  ('Astral Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'juggernaut'),
  ('Astral Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'juggernaut'),
  ('Astral Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'juggernaut'),
  ('Astral Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'juggernaut'),
  ('Celestial Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'juggernaut'),
  ('Celestial Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'juggernaut'),
  ('Celestial Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'juggernaut'),
  ('Celestial Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'juggernaut'),
  ('Celestial Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'juggernaut'),
  ('Eternity Sword', 'weapon', 'longsword-juggernaut', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'juggernaut'),

  ('Rustcut Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'juggernaut'),
  ('Ironbound Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'juggernaut'),
  ('Steelfang Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'juggernaut'),
  ('Bloodedge Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'juggernaut'),
  ('Battleworn Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'juggernaut'),
  ('Warforged Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'juggernaut'),
  ('Grimsteel Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'juggernaut'),
  ('Ashfallen Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'juggernaut'),
  ('Direheart Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'juggernaut'),
  ('Bramblefang Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'juggernaut'),
  ('Nightstrike Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'juggernaut'),
  ('Frostbrand Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'juggernaut'),
  ('Stormedge Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'juggernaut'),
  ('Ironclad Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'juggernaut'),
  ('Bloodoath Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'juggernaut'),
  ('Grimward Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'juggernaut'),
  ('Skullrend Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'juggernaut'),
  ('Doomforge Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'juggernaut'),
  ('Wrathbound Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'juggernaut'),
  ('Shadowstrike Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'juggernaut'),
  ('Vengeance Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'juggernaut'),
  ('Warbringer Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'juggernaut'),
  ('Astral Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'juggernaut'),
  ('Astral Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'juggernaut'),
  ('Astral Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'juggernaut'),
  ('Astral Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'juggernaut'),
  ('Astral Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'juggernaut'),
  ('Celestial Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'juggernaut'),
  ('Celestial Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'juggernaut'),
  ('Celestial Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'juggernaut'),
  ('Celestial Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'juggernaut'),
  ('Celestial Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'juggernaut'),
  ('Eternity Blade', 'weapon', 'blade-juggernaut', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'juggernaut'),

  ('Boneshatter Maul', 'weapon', 'greatmaul', '{"physical_attack":7,"dexterity":1}'::jsonb, 8, 'juggernaut'),
  ('Skullcrusher Maul', 'weapon', 'greatmaul', '{"physical_attack":10,"dexterity":2}'::jsonb, 15, 'juggernaut'),
  ('Earthshaker Maul', 'weapon', 'greatmaul', '{"physical_attack":13,"dexterity":2}'::jsonb, 20, 'juggernaut'),
  ('Stonebreaker Maul', 'weapon', 'greatmaul', '{"physical_attack":17,"dexterity":3}'::jsonb, 25, 'juggernaut'),
  ('Titanfist Maul', 'weapon', 'greatmaul', '{"physical_attack":20,"dexterity":3}'::jsonb, 30, 'juggernaut'),
  ('Ragehammer Maul', 'weapon', 'greatmaul', '{"physical_attack":24,"dexterity":4}'::jsonb, 35, 'juggernaut'),
  ('Ironquake Maul', 'weapon', 'greatmaul', '{"physical_attack":29,"dexterity":4}'::jsonb, 40, 'juggernaut'),
  ('Doomcrusher Maul', 'weapon', 'greatmaul', '{"physical_attack":33,"dexterity":5}'::jsonb, 45, 'juggernaut'),
  ('Warbreaker Maul', 'weapon', 'greatmaul', '{"physical_attack":38,"dexterity":6}'::jsonb, 50, 'juggernaut'),
  ('Direquake Maul', 'weapon', 'greatmaul', '{"physical_attack":43,"dexterity":6}'::jsonb, 55, 'juggernaut'),
  ('Bloodhammer Maul', 'weapon', 'greatmaul', '{"physical_attack":49,"dexterity":7}'::jsonb, 60, 'juggernaut'),
  ('Grimforge Maul', 'weapon', 'greatmaul', '{"physical_attack":54,"dexterity":8}'::jsonb, 65, 'juggernaut'),
  ('Thunderfist Maul', 'weapon', 'greatmaul', '{"physical_attack":60,"dexterity":9}'::jsonb, 70, 'juggernaut'),
  ('Wrathquake Maul', 'weapon', 'greatmaul', '{"physical_attack":67,"dexterity":10}'::jsonb, 75, 'juggernaut'),
  ('Ashenmaul Maul', 'weapon', 'greatmaul', '{"physical_attack":73,"dexterity":11}'::jsonb, 80, 'juggernaut'),
  ('Stormbreaker Maul', 'weapon', 'greatmaul', '{"physical_attack":80,"dexterity":12}'::jsonb, 85, 'juggernaut'),
  ('Nightcrusher Maul', 'weapon', 'greatmaul', '{"physical_attack":88,"dexterity":13}'::jsonb, 90, 'juggernaut'),
  ('Doombringer Maul', 'weapon', 'greatmaul', '{"physical_attack":95,"dexterity":14}'::jsonb, 95, 'juggernaut'),
  ('Vengeful Maul', 'weapon', 'greatmaul', '{"physical_attack":103,"dexterity":15}'::jsonb, 100, 'juggernaut'),
  ('Battlecrusher Maul', 'weapon', 'greatmaul', '{"physical_attack":111,"dexterity":17}'::jsonb, 105, 'juggernaut'),
  ('Soulrender Maul', 'weapon', 'greatmaul', '{"physical_attack":120,"dexterity":18}'::jsonb, 110, 'juggernaut'),
  ('Godslayer Maul', 'weapon', 'greatmaul', '{"physical_attack":128,"dexterity":19}'::jsonb, 115, 'juggernaut'),
  ('Astral Maul', 'weapon', 'greatmaul', '{"physical_attack":137,"dexterity":21}'::jsonb, 120, 'juggernaut'),
  ('Astral Maul', 'weapon', 'greatmaul', '{"physical_attack":139,"dexterity":21}'::jsonb, 121, 'juggernaut'),
  ('Astral Maul', 'weapon', 'greatmaul', '{"physical_attack":141,"dexterity":21}'::jsonb, 122, 'juggernaut'),
  ('Astral Maul', 'weapon', 'greatmaul', '{"physical_attack":143,"dexterity":21}'::jsonb, 123, 'juggernaut'),
  ('Astral Maul', 'weapon', 'greatmaul', '{"physical_attack":145,"dexterity":22}'::jsonb, 124, 'juggernaut'),
  ('Celestial Maul', 'weapon', 'greatmaul', '{"physical_attack":147,"dexterity":22}'::jsonb, 125, 'juggernaut'),
  ('Celestial Maul', 'weapon', 'greatmaul', '{"physical_attack":149,"dexterity":22}'::jsonb, 126, 'juggernaut'),
  ('Celestial Maul', 'weapon', 'greatmaul', '{"physical_attack":151,"dexterity":23}'::jsonb, 127, 'juggernaut'),
  ('Celestial Maul', 'weapon', 'greatmaul', '{"physical_attack":153,"dexterity":23}'::jsonb, 128, 'juggernaut'),
  ('Celestial Maul', 'weapon', 'greatmaul', '{"physical_attack":154,"dexterity":23}'::jsonb, 129, 'juggernaut'),
  ('Eternity Maul', 'weapon', 'greatmaul', '{"physical_attack":156,"dexterity":23}'::jsonb, 130, 'juggernaut'),

  ('Rawhide Shield', 'quiver', 'shield', '{"physical_defense":3,"max_hp":10}'::jsonb, 7, 'juggernaut'),
  ('Banded Shield', 'quiver', 'shield', '{"physical_defense":7,"max_hp":20}'::jsonb, 17, 'juggernaut'),
  ('Ridged Shield', 'quiver', 'shield', '{"physical_defense":11,"max_hp":35}'::jsonb, 27, 'juggernaut'),
  ('Ironbound Shield', 'quiver', 'shield', '{"physical_defense":15,"max_hp":50}'::jsonb, 37, 'juggernaut'),
  ('Warguard Shield', 'quiver', 'shield', '{"physical_defense":19,"max_hp":65}'::jsonb, 45, 'juggernaut'),
  ('Bloodwall Shield', 'quiver', 'shield', '{"physical_defense":22,"max_hp":80}'::jsonb, 52, 'juggernaut'),
  ('Stormward Shield', 'quiver', 'shield', '{"physical_defense":30,"max_hp":110}'::jsonb, 67, 'juggernaut'),
  ('Direward Shield', 'quiver', 'shield', '{"physical_defense":39,"max_hp":150}'::jsonb, 82, 'juggernaut'),
  ('Grimguard Shield', 'quiver', 'shield', '{"physical_defense":49,"max_hp":200}'::jsonb, 97, 'juggernaut'),
  ('Warlord Shield', 'quiver', 'shield', '{"physical_defense":60,"max_hp":260}'::jsonb, 112, 'juggernaut'),
  ('Astral Shield', 'quiver', 'shield', '{"physical_defense":66,"max_hp":300}'::jsonb, 120, 'juggernaut'),
  ('Celestial Shield', 'quiver', 'shield', '{"physical_defense":70,"max_hp":330}'::jsonb, 125, 'juggernaut'),
  ('Eternity Shield', 'quiver', 'shield', '{"physical_defense":74,"max_hp":360}'::jsonb, 130, 'juggernaut'),

  ('Rawhide Helmet', 'hat', 'helmet', '{"physical_defense":3}'::jsonb, 7, 'juggernaut'),
  ('Banded Helmet', 'hat', 'helmet', '{"physical_defense":7}'::jsonb, 17, 'juggernaut'),
  ('Ridged Helmet', 'hat', 'helmet', '{"physical_defense":11}'::jsonb, 27, 'juggernaut'),
  ('Ironbrow Helmet', 'hat', 'helmet', '{"physical_defense":15}'::jsonb, 37, 'juggernaut'),
  ('Warcrest Helmet', 'hat', 'helmet', '{"physical_defense":19}'::jsonb, 45, 'juggernaut'),
  ('Bloodguard Helmet', 'hat', 'helmet', '{"physical_defense":22}'::jsonb, 52, 'juggernaut'),
  ('Stormcrest Helmet', 'hat', 'helmet', '{"physical_defense":30}'::jsonb, 67, 'juggernaut'),
  ('Direplate Helmet', 'hat', 'helmet', '{"physical_defense":39}'::jsonb, 82, 'juggernaut'),
  ('Grimvisage Helmet', 'hat', 'helmet', '{"physical_defense":49}'::jsonb, 97, 'juggernaut'),
  ('Warlord Helmet', 'hat', 'helmet', '{"physical_defense":60}'::jsonb, 112, 'juggernaut'),
  ('Astral Helmet', 'hat', 'helmet', '{"physical_defense":66}'::jsonb, 120, 'juggernaut'),
  ('Celestial Helmet', 'hat', 'helmet', '{"physical_defense":70}'::jsonb, 125, 'juggernaut'),
  ('Eternity Helmet', 'hat', 'helmet', '{"physical_defense":74}'::jsonb, 130, 'juggernaut'),

  ('Rawhide Armor', 'coat', 'armor', '{"physical_defense":3,"magic_defense":2}'::jsonb, 7, 'juggernaut'),
  ('Banded Armor', 'coat', 'armor', '{"physical_defense":7,"magic_defense":4}'::jsonb, 17, 'juggernaut'),
  ('Ridged Armor', 'coat', 'armor', '{"physical_defense":11,"magic_defense":6}'::jsonb, 27, 'juggernaut'),
  ('Ironweave Armor', 'coat', 'armor', '{"physical_defense":15,"magic_defense":8}'::jsonb, 37, 'juggernaut'),
  ('Warplate Armor', 'coat', 'armor', '{"physical_defense":19,"magic_defense":10}'::jsonb, 45, 'juggernaut'),
  ('Bloodforged Armor', 'coat', 'armor', '{"physical_defense":22,"magic_defense":11}'::jsonb, 52, 'juggernaut'),
  ('Stormguard Armor', 'coat', 'armor', '{"physical_defense":30,"magic_defense":15}'::jsonb, 67, 'juggernaut'),
  ('Ashenplate Armor', 'coat', 'armor', '{"physical_defense":39,"magic_defense":20}'::jsonb, 82, 'juggernaut'),
  ('Grimhide Armor', 'coat', 'armor', '{"physical_defense":49,"magic_defense":25}'::jsonb, 97, 'juggernaut'),
  ('Warlord Armor', 'coat', 'armor', '{"physical_defense":60,"magic_defense":30}'::jsonb, 112, 'juggernaut'),
  ('Astral Armor', 'coat', 'armor', '{"physical_defense":66,"magic_defense":33}'::jsonb, 120, 'juggernaut'),
  ('Celestial Armor', 'coat', 'armor', '{"physical_defense":70,"magic_defense":35}'::jsonb, 125, 'juggernaut'),
  ('Eternity Armor', 'coat', 'armor', '{"physical_defense":74,"magic_defense":37}'::jsonb, 130, 'juggernaut');
